apiVersion: v2
name: eurooffice
description: Euro-Office Document Server Helm chart for Nextcloud integration
type: application
version: 1.1.0
appVersion: "9.3.3"
keywords:
  - eurooffice
  - documentserver
  - office
  - nextcloud
