replicaCount: 1

image:
  repository: ghcr.io/euro-office/documentserver
  tag: "9.3.1"
  pullPolicy: IfNotPresent

jwt:
  enabled: true
  secret: "CHANGE_ME"
  header: "Authorization"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

persistence:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}